#!/bin/sh

set -e

# Bootstrap config
lb config noauto \
	--clean \
	--mode "debian" \
	--system "live" \
	--architectures "amd64" \
	--distribution "bookworm" \
	--archive-areas "main contrib non-free" \
	--apt-source-archives "false" \
	--security "true" \
	--updates "true" \
	--backports "true" \
	--firmware-binary "true" \
	--firmware-chroot "true" \
	--ignore-system-defaults \
	--chroot-squashfs-compression-type lz4 \
"${@}"

# Packages
wget -P config/packages.chroot/ -nc -i packages.chroot.txt
dpkg-name config/packages.chroot/*
